/**
 * Section-by-section prompt builders for structured LLM output.
 *
 * Architecture:
 * - Each report section is defined with a fixed ID, title, and prompt builder
 * - The LLM is called once per narrative section (not once for the whole report)
 * - The LLM returns ONLY prose content — no headings, no section titles, no markdown structure
 * - Section ordering, titles, and IDs are 100% controlled by code
 *
 * Sections that are deterministic (financial_statements, key_metrics, data_sources)
 * are NOT generated by the LLM — they're built in code by other modules.
 */

import type { AnalysisContext } from '@dolph/shared';
import type { AnalysisInsights } from '../analyzer.js';
import { formatCompactCurrency } from '@dolph/shared';

// ── Section Definitions ─────────────────────────────────────────

export interface SectionDef {
  id: string;
  title: string;
  /** If true, this section is built deterministically (no LLM). */
  deterministic: boolean;
  /** Build the LLM prompt for this section. Only called if deterministic=false. */
  buildPrompt?: (data: SectionData) => string;
}

export interface SectionData {
  ticker: string;
  companyName: string;
  fxNote: string;
  dataBlock: string;
  context: AnalysisContext;
  insights: Record<string, AnalysisInsights>;
}

/**
 * Ordered list of sections for a SINGLE-COMPANY report.
 * This is the canonical order — every report follows it exactly.
 */
export const SINGLE_REPORT_SECTIONS: SectionDef[] = [
  {
    id: 'executive_summary',
    title: 'Executive Summary',
    deterministic: false,
    buildPrompt: (data) => `Write an executive summary for ${data.companyName} (${data.ticker}).

DATA:
${data.dataBlock}

INSTRUCTIONS:
- Write exactly 3-4 sentences that a non-finance person could understand
- Include the most important headline numbers (revenue, net income, key ratios)
- Reference specific dollar amounts and percentages from the DATA
- Do NOT use any headings or section titles — write only the paragraph content
- Do NOT use vague phrases like "growing steadily" or "performing well"
- Format large numbers as $X.XB (billions) or $X.XM (millions)

Output ONLY the paragraph text. No headings, no bullet points, no markdown formatting.`,
  },
  // key_metrics is deterministic (table built in code)
  {
    id: 'key_metrics',
    title: 'Key Metrics Dashboard',
    deterministic: true,
  },
  {
    id: 'trend_analysis',
    title: 'Trend Analysis',
    deterministic: false,
    buildPrompt: (data) => `Write a trend analysis for ${data.companyName} (${data.ticker}).

DATA:
${data.dataBlock}

INSTRUCTIONS:
- Analyze the top 3-5 most significant trends in the data
- For each trend, write 2-3 sentences explaining what happened and why it matters
- Reference specific numbers, time periods, and growth rates
- Use ### subheadings for each trend (e.g., "### Revenue Growth")
- Do NOT start with a top-level ## heading — write the content directly
- Every sentence must cite a specific figure from the DATA

Output the trend analysis content only. No section title.`,
  },
  {
    id: 'risk_factors',
    title: 'Risk Factors',
    deterministic: false,
    buildPrompt: (data) => `Write a risk factors section for ${data.companyName} (${data.ticker}).

DATA:
${data.dataBlock}

INSTRUCTIONS:
- Summarize the top 3-5 risks in 1-2 sentences each
- If red flags are listed in the data, incorporate them with specific numbers
- If 10-K risk factor text is available in the data, synthesize those
- Otherwise derive risks from the financial metrics and trends
- Use a numbered list (1. 2. 3.) for each risk
- Do NOT start with a top-level heading — write the content directly
- Every risk must reference a specific number or metric

Output the risk factors content only. No section title.`,
  },
  // financial_statements is deterministic (tables built in code)
  {
    id: 'financial_statements',
    title: 'Financial Statements',
    deterministic: true,
  },
  {
    id: 'analyst_notes',
    title: 'Analyst Notes',
    deterministic: false,
    buildPrompt: (data) => `Write analyst notes for ${data.companyName} (${data.ticker}).

DATA:
${data.dataBlock}

INSTRUCTIONS:
- Write exactly 2-3 paragraphs of synthesis
- Paragraph 1: What story do the numbers tell? What is the company's financial narrative?
- Paragraph 2: What questions should an analyst investigate further?
- Paragraph 3 (optional): Forward-looking considerations based on the data
- Every paragraph must reference specific numbers from the DATA
- Do NOT use any headings — write only paragraphs
- Do NOT use vague language — every claim needs a number
- Do NOT hallucinate numbers not in the DATA

Output the paragraphs only. No section title, no bullet points.`,
  },
  // data_sources is deterministic (built in code)
  {
    id: 'data_sources',
    title: 'Data Sources',
    deterministic: true,
  },
];

/**
 * Ordered list of sections for a COMPARISON report.
 */
export const COMPARISON_REPORT_SECTIONS: SectionDef[] = [
  {
    id: 'executive_summary',
    title: 'Executive Summary',
    deterministic: false,
    buildPrompt: (data) => {
      const tickers = data.context.tickers;
      return `Write a comparison executive summary for ${tickers.join(' vs ')}.

DATA:
${data.dataBlock}

INSTRUCTIONS:
- Write exactly 3-4 sentences comparing these companies at a high level
- Include the most important differentiating metrics
- Reference specific dollar amounts and percentages from the DATA
- Do NOT use any headings — write only the paragraph content
- Format large numbers as $X.XB (billions) or $X.XM (millions)

Output ONLY the paragraph text.`;
    },
  },
  {
    id: 'key_metrics',
    title: 'Key Metrics Comparison',
    deterministic: true,
  },
  {
    id: 'relative_strengths',
    title: 'Relative Strengths',
    deterministic: false,
    buildPrompt: (data) => {
      const tickers = data.context.tickers;
      return `Write a relative strengths analysis for ${tickers.join(' vs ')}.

DATA:
${data.dataBlock}

INSTRUCTIONS:
- For each company, write 2-3 bullet points on their competitive advantages
- Base every point on specific numbers from the DATA
- Use ### subheadings for each company (e.g., "### AAPL", "### MSFT")
- Do NOT start with a top-level heading
- Do NOT use vague language — every bullet must cite a specific number

Output the relative strengths content only.`;
    },
  },
  {
    id: 'risk_factors',
    title: 'Risk Comparison',
    deterministic: false,
    buildPrompt: (data) => {
      const tickers = data.context.tickers;
      return `Write a risk comparison for ${tickers.join(' vs ')}.

DATA:
${data.dataBlock}

INSTRUCTIONS:
- Compare financial risk between the companies
- Reference specific ratios, margins, and trends from the DATA
- Write 2-3 paragraphs
- Do NOT start with a top-level heading
- Every claim must cite a specific figure

Output the risk comparison content only.`;
    },
  },
  {
    id: 'financial_statements',
    title: 'Financial Statements',
    deterministic: true,
  },
  {
    id: 'analyst_notes',
    title: 'Analyst Notes',
    deterministic: false,
    buildPrompt: (data) => {
      const tickers = data.context.tickers;
      return `Write analyst notes comparing ${tickers.join(' vs ')}.

DATA:
${data.dataBlock}

INSTRUCTIONS:
- Write 2-3 paragraphs of synthesis on how these companies compare
- What does the data tell us about their relative positions?
- What should an analyst investigate further?
- Reference specific numbers throughout
- Do NOT use headings — write only paragraphs

Output the paragraphs only.`;
    },
  },
  {
    id: 'data_sources',
    title: 'Data Sources',
    deterministic: true,
  },
];

// ── Data Block Builder ──────────────────────────────────────────

/**
 * Build the structured data block that gets included in every LLM prompt.
 * This is the same data for all sections — consistent context.
 */
export function buildDataBlock(
  context: AnalysisContext,
  insights: Record<string, AnalysisInsights>,
): string {
  const parts: string[] = [];

  for (const ticker of context.tickers) {
    const tickerInsights = insights[ticker];
    const facts = context.facts[ticker];
    const ratios = context.ratios[ticker] || [];
    const trends = context.trends[ticker] || [];
    const filingContent = context.filing_content[ticker];

    parts.push(`# ${ticker} — ${facts?.company_name || ticker}`);
    if (facts?.fx_note) {
      parts.push(`Note: All values converted to USD (${facts.fx_note})`);
    }
    parts.push('');

    // Key metrics
    if (tickerInsights?.keyMetrics && Object.keys(tickerInsights.keyMetrics).length > 0) {
      parts.push('## Key Metrics');
      for (const [name, data] of Object.entries(tickerInsights.keyMetrics)) {
        const changeStr = data.change !== null
          ? ` (YoY: ${(data.change * 100).toFixed(1)}%)`
          : '';
        parts.push(`- ${name}: ${formatValue(data.current, data.unit)}${changeStr}`);
      }
      parts.push('');
    }

    // Ratios
    if (ratios.length > 0) {
      parts.push('## Financial Ratios');
      for (const r of ratios) {
        parts.push(`- ${r.display_name}: ${r.value.toFixed(4)} (${r.formula}) [period: ${r.period}]`);
      }
      parts.push('');
    }

    // Trends
    if (trends.length > 0) {
      parts.push('## Trends');
      for (const t of trends) {
        const cagrStr = t.cagr !== null ? `CAGR: ${(t.cagr * 100).toFixed(1)}%` : 'CAGR: N/A';
        const values = t.values.slice(-5).map(v =>
          `${v.period}: ${formatLargeNumber(v.value)}`,
        ).join(', ');
        parts.push(`- ${t.metric}: ${cagrStr} | Recent: ${values}`);
      }
      parts.push('');
    }

    // Red flags
    if (tickerInsights?.redFlags && tickerInsights.redFlags.length > 0) {
      parts.push('## Red Flags');
      for (const f of tickerInsights.redFlags) {
        parts.push(`- [${f.severity}] ${f.flag}: ${f.detail}`);
      }
      parts.push('');
    }

    // Strengths
    if (tickerInsights?.strengths && tickerInsights.strengths.length > 0) {
      parts.push('## Strengths');
      for (const s of tickerInsights.strengths) {
        parts.push(`- ${s.detail}`);
      }
      parts.push('');
    }

    // Risk factors from filing
    if (filingContent) {
      const riskSection = filingContent.sections.find(s =>
        s.title.toLowerCase().includes('risk factor'),
      );
      if (riskSection && riskSection.content.length > 0) {
        parts.push('## Risk Factors from Filing (excerpt)');
        parts.push(riskSection.content.slice(0, 3000));
        parts.push('');
      }
    }

    // Comparison data
    if (context.comparison) {
      parts.push('## Comparison Matrix');
      for (const m of context.comparison.metrics) {
        const values = context.tickers
          .map(t => `${t}: ${m.values[t] !== null && m.values[t] !== undefined ? formatLargeNumber(m.values[t]!) : 'N/A'}`)
          .join(', ');
        parts.push(`- ${m.metric}: ${values}`);
      }
      parts.push('');
    }
  }

  return parts.join('\n');
}

// ── Formatting Utilities ────────────────────────────────────────

function formatValue(value: number, unit: string): string {
  if (unit === '%') return `${(value * 100).toFixed(1)}%`;
  if (unit === 'x') return `${value.toFixed(2)}x`;
  if (unit === 'USD') return formatLargeNumber(value);
  if (unit === 'USD/share' || unit === 'USD/shares') return `$${value.toFixed(2)}`;
  return `${value}`;
}

function formatLargeNumber(n: number): string {
  return formatCompactCurrency(n, { smallDecimals: 2, compactDecimals: 1 });
}
