"use client";

import { useCallback } from "react";

interface ReportSection {
  id: string;
  title: string;
  content: string;
}

interface ExportButtonsProps {
  sections: ReportSection[];
  tickers: string[];
}

export function ExportButtons({ sections, tickers }: ExportButtonsProps) {
  const generateMarkdown = useCallback(() => {
    const lines: string[] = [
      `# ${tickers.join(" vs ")} Financial Analysis`,
      "",
      `*Generated by Dolph on ${new Date().toLocaleDateString()}*`,
      "",
    ];

    for (const section of sections) {
      lines.push(`## ${section.title}`, "", section.content, "");
    }

    lines.push("---", "*Data sourced from SEC EDGAR. Not financial advice.*");
    return lines.join("\n");
  }, [sections, tickers]);

  const downloadMarkdown = useCallback(() => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `dolph-${tickers.join("-").toLowerCase()}-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [generateMarkdown, tickers]);

  const copyToClipboard = useCallback(async () => {
    const md = generateMarkdown();
    await navigator.clipboard.writeText(md);
  }, [generateMarkdown]);

  if (sections.length === 0) return null;

  return (
    <div className="flex gap-2">
      <button
        onClick={downloadMarkdown}
        className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-neutral-400 bg-[#1a1a1a] border border-[#333] rounded-md hover:text-white hover:border-[#444] transition-colors"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        Markdown
      </button>
      <button
        onClick={copyToClipboard}
        className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-neutral-400 bg-[#1a1a1a] border border-[#333] rounded-md hover:text-white hover:border-[#444] transition-colors"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
        </svg>
        Copy
      </button>
    </div>
  );
}
