import type { AnalysisContext } from '@shawyan/shared';
import type { AnalysisInsights } from './analyzer.js';
import { analyzeData } from './analyzer.js';
import { buildReportModel, type ReportModel } from './report-model.js';
import {
  generateChartsForReportModel,
  type ChartSet,
} from './charts.js';

export interface ChartPeriodLock {
  current: string | null;
  prior: string | null;
}

export type CanonicalPeriodLocks = Record<string, ChartPeriodLock>;

export interface CanonicalReportPackage {
  context: AnalysisContext;
  insights: Record<string, AnalysisInsights>;
  reportModel: ReportModel;
  periodLocks: CanonicalPeriodLocks;
  charts: ChartSet;
}

export function buildCanonicalReportPackage(
  context: AnalysisContext,
): CanonicalReportPackage {
  const insights = analyzeData(context, context.policy);
  const reportModel = buildReportModel(context, insights);
  const periodLocks = Object.fromEntries(
    context.tickers.map(ticker => [ticker, {
      current: insights[ticker]?.snapshotPeriod ?? null,
      prior: insights[ticker]?.priorPeriod ?? null,
    }]),
  ) as CanonicalPeriodLocks;
  const charts = generateChartsForReportModel(context, reportModel);
  return {
    context,
    insights,
    reportModel,
    periodLocks,
    charts,
  };
}

export function requireCanonicalReportPackage(
  canonicalPackage: CanonicalReportPackage | undefined,
  caller: string,
): CanonicalReportPackage {
  if (!canonicalPackage) {
    throw new Error(`${caller} requires a sealed canonical report package generated by runPipeline().`);
  }
  return canonicalPackage;
}
