import type { AnalysisContext } from '@dolph/shared';
import type { AnalysisInsights } from './analyzer.js';
import { analyzeData } from './analyzer.js';
import { buildReportModel, type ReportModel } from './report-model.js';

export interface CanonicalReportPackage {
  context: AnalysisContext;
  insights: Record<string, AnalysisInsights>;
  reportModel: ReportModel;
}

export function buildCanonicalReportPackage(
  context: AnalysisContext,
): CanonicalReportPackage {
  const insights = analyzeData(context, context.policy);
  const reportModel = buildReportModel(context, insights);
  return {
    context,
    insights,
    reportModel,
  };
}

export function requireCanonicalReportPackage(
  canonicalPackage: CanonicalReportPackage | undefined,
  caller: string,
): CanonicalReportPackage {
  if (!canonicalPackage) {
    throw new Error(`${caller} requires a sealed canonical report package generated by runPipeline().`);
  }
  return canonicalPackage;
}
